name: contao-book

services:
    appserver:
        type: php:8.2
        via: cli

tooling:
    composer:
        service: appserver
        cmd: composer

    ecs-init:
        service: appserver
        cmd: composer install -d tools/ecs

    rector-init:
        service: appserver
        cmd: composer install -d tools/rector

    ecs:
        service: appserver
        cmd: composer ecs

    rector:
        service: appserver
        cmd: composer rector
